name: build and test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v1

      - name: "attach git head"
        run: git checkout "${GITHUB_REF#refs/heads/}"

      - name: "setup JDK"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "get generic mvg-info"
        uses: ModelingValueGroup/generic-info@master

      - name: "get buildTools"
        uses: ModelingValueGroup/buildTools@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "prepare"
        run:  |
          cat <<EOF >build.properties
          jdk.home.11=$JAVA_HOME
          path.variable.mps_home=./MPS
          EOF

      - name: "(re)generate some files"
        run:  |
          . <(java -jar buildTools.jar)
          generateAll
          correctEols
          correctHeaders header

      - name: "download dependencies (MPS and jars from pom)"
        run:  |
          . <(java -jar buildTools.jar)
          . project.sh
          getAllDependencies ${{ secrets.GITHUB_TOKEN }} "${{ secrets.SCALEWAY_ACCESS_KEY }}" "${{ secrets.SCALEWAY_SECRET_KEY }}"
          installMps "$mpsDir" "$mpsVersion"

      - name: "runtime: build"
        run:  ant

      - name: "runtime: test"
        run:  ant test

      - name: "runtime: generate javadoc"
        run:  ant javadoc

      - name: "dclare-plugin: build"
        run:  |
          . project.sh
          ant -debug -Dmps_home="$mpsDir" -f mps_build.xml generate build

      - name: "publish action-artifact zip"
        uses: actions/upload-artifact@v1
        with:
          name: DclareForMPS.zip
          path: build/artifacts/DclareForMPS/DclareForMPS.zip

      - name: "push changes back to github"
        run:  |
          . <(java -jar buildTools.jar)
          pushBackToGithub "${{ secrets.GITHUB_TOKEN }}" "automation@modelingvalue.com" "adjusted files [by github actions]"
